"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { NameModal } from "./name-modal";

/**
 * Wrapper to show NameModal for auto-registered users
 * Auto-registered users have names like "email" or "username" (from email prefix)
 */
export function NameModalWrapper() {
    const { data: session, status } = useSession();
    const [showNameModal, setShowNameModal] = useState(false);

    useEffect(() => {
        if (status === "authenticated" && session?.user) {
            const userName = session.user.name || "";
            const userEmail = session.user.email || "";

            // Check if name looks auto-generated (email prefix or contains @)
            const isAutoGeneratedName =
                userName === userEmail.split("@")[0] ||
                userName.includes("@") ||
                userName.length < 2;

            if (isAutoGeneratedName) {
                const timer = setTimeout(() => setShowNameModal(true), 0);
                return () => clearTimeout(timer);
            }
        }
    }, [session, status]);

    return <NameModal open={showNameModal} onOpenChange={setShowNameModal} />;
}
